spring:
  data:
    mongodb:
      uri: "mongodb://masterdata:master123@localhost:27017/masterdata"
  rabbitmq:
    host: localhost
    port: 5672

management:
  influx:
    metrics:
      export:
        api-version: v2
        auto-create-db: true
        bucket: ledgerservice-bucket
        user-name: influx-user
        password: influx-password
        org: ledgerservice-org
        uri: "http://localhost:8086"
        db: ledgerservice-db
        token: 2b0c2328c5a88731cef2dfbf8ac054e7a3792a43a20a931cb7595fef68105d55
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
