spring:
  data:
    mongodb:
      uri: "mongodb://masterdata:master123@mongo:27017/masterdata"
  rabbitmq:
    host: rabbitmq
    port: 5672

management:
  influx:
    metrics:
      export:
        api-version: v2
        auto-create-db: true
        bucket: ledgerservice-bucket
        user-name: influx-user
        password: influx-password
        org: ledgerservice-org
        uri: "http://influxdb:8086"
  zipkin:
    tracing:
      endpoint: "http://jaeger:9411/api/v2/spans"
