spring:
  application:
    name: masterdata
  graphql:
    graphiql:
      enabled: true
      path: /graphql

management:
  endpoint:
    beans:
      enabled: true
    caches:
      enabled: true
    conditions:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
app:
  rest:
    security:
      common:
        api-path: /graphql

